// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCneHg4YOEnNODCeqC-22tNduDyBrU_ADY',
    appId: '1:1048203336403:web:56df6372d9ce81f43a5226',
    messagingSenderId: '1048203336403',
    projectId: 'harshit-jan-project-2024',
    authDomain: 'harshit-jan-project-2024.firebaseapp.com',
    storageBucket: 'harshit-jan-project-2024.appspot.com',
    measurementId: 'G-PZHG1STJTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeBkcsAPL-c37vkxAZ0QNO5BTpRU_Thbs',
    appId: '1:1048203336403:android:5bf58bf01038cb183a5226',
    messagingSenderId: '1048203336403',
    projectId: 'harshit-jan-project-2024',
    storageBucket: 'harshit-jan-project-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc2RMwUopItArU4TozolaRDH0hMmT9v88',
    appId: '1:1048203336403:ios:9501ded3880f8afe3a5226',
    messagingSenderId: '1048203336403',
    projectId: 'harshit-jan-project-2024',
    storageBucket: 'harshit-jan-project-2024.appspot.com',
    androidClientId: '1048203336403-7hsumfjb695a10khon461jok31o3bijj.apps.googleusercontent.com',
    iosClientId: '1048203336403-15tls0a4dh95fk07s2tn6tchfd2m1eu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendzo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc2RMwUopItArU4TozolaRDH0hMmT9v88',
    appId: '1:1048203336403:ios:02e1cde36e8e901d3a5226',
    messagingSenderId: '1048203336403',
    projectId: 'harshit-jan-project-2024',
    storageBucket: 'harshit-jan-project-2024.appspot.com',
    androidClientId: '1048203336403-7hsumfjb695a10khon461jok31o3bijj.apps.googleusercontent.com',
    iosClientId: '1048203336403-8tdncc5oilbj3sic4f4t0l3pabmrl002.apps.googleusercontent.com',
    iosBundleId: 'com.example.friendzo.RunnerTests',
  );
}
